### ISSUE TITLE
感谢提供源代码，我基于你的代码，移植了Ruby版的gem包

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [itbdw/ip-database#11]
在移植时，我发现有些少数名族的城市名不好提取。比如“四川省凉山州西昌市”，“凉山州”是城市，“西昌市”是县。又如”内蒙古锡林郭勒盟“，”锡林郭勒盟“是城市。

要实现准确提取，我想可能需要中国的城市库。要实现这个功能，需要花些时间整理省市区县的数据。不知你在业务应用中是否已经做个这个事了？能否共享出来？

附上我移植的Ruby Gem地址：https://github.com/xiaohui-zhangxh/ip_locator_cn

**Comment by itbdw** [comment]
确实，几年前没注意到这个问题。

城市库应该可以搜索到，或者抓一下app的接口，比如淘宝收货地址，你试一下吧
