### ISSUE TITLE
大佬，为什么有些ip会报错，求指教要怎么改

### ISSUE THREAD

**Issue by Git-cup** [itbdw/ip-database#13]
![QQ截图20190819185048](https://user-images.githubusercontent.com/22374504/63260083-a2095a80-c2b2-11e9-9977-8577ff0e6214.png)

**Comment by itbdw** [comment]
请问你是怎么出现的呢，我简单测试没有复现。

PHP版本是多少，调用的代码方便发一下么

➜  ip-database git:(master) php tests/ip.php -i 61.244.30.30

**Comment by Git-cup** [comment]
用的是 php7，我这边测试发现，只要是香港的IP都会报错，所以我注释了下面这一段代码
![注释](https://user-images.githubusercontent.com/22374504/63341524-f6c4d800-c37b-11e9-9b78-d36d57292c08.png)
这是一些香港的ip：
61.244.66.190
61.244.30.30
61.244.30.30
61.244.210.244
61.244.16.190

**Comment by itbdw** [comment]
我知道了，你的系统应该是缺少 php-mbstring 扩展

**Comment by Git-cup** [comment]
非常非常非常感谢大佬，已经好了
