### ISSUE TITLE
返回 无数据2020年1月15日IP数据

### ISSUE THREAD

**Issue by pangongzi** [itbdw/ip-database#16]
["ip"]=> string(14) "115.226.116.52" ["beginip"]=> string(13) "255.255.255.0" ["endip"]=> string(15) "255.255.255.255" ["country"]=> string(8) "纯真网络" ["area"]=> string(19) "2020年1月15日IP数据"

**Comment by itbdw** [comment]
这个不能保证都有的，数据是纯真那边的
