### ISSUE TITLE
用最新纯真IP库,PHP版本7.2提升错误

### ISSUE THREAD

**Issue by hulang** [itbdw/ip-database#17]
fseek() expects parameter 2 to be integer, float given

**Comment by hulang** [comment]
@itbdw 。。。。。。。。

**Comment by itbdw** [comment]
方便粘贴下测试的ip吗

**Comment by hulang** [comment]
@itbdw 47.115.14.70

**Comment by itbdw** [comment]
php -v
PHP 7.2.3 (cli) (built: Mar 22 2018 22:10:51) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

ini_set("display_errors", "on");
ini_set("error_reporting", -1);

未能复现

**Comment by hulang** [comment]
@itbdw 好像又可以了。感谢作者的回复。。
