### ISSUE TITLE
直接使用file_get_contents下载 会出错。 需要添加 header 信息。

### ISSUE THREAD

**Issue by hibijun** [itbdw/ip-database#20]
$copywrite = curls_get("http://update.cz88.net/ip/copywrite.rar");
$qqwry      = curls_get("http://update.cz88.net/ip/qqwry.rar");

function curls_get($url)
{
    $header = ["User-Agent:Mozilla/3.0 (compatible; Indy Library)","Accept:text/html, */*"];
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 600,
        CURLOPT_CUSTOMREQUEST => "GET",
        CURLOPT_HTTPHEADER => $header,
        CURLOPT_URL => $url,
    ));
    $res = curl_exec($curl);
    curl_close($curl);
    return $res;
}

**Comment by itbdw** [comment]
👍 good

**Comment by itbdw** [comment]
我本地更新后，下载的还是错的 @hibijun 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
<title>406 - ?ͻ?????????????? MIME ???͵?????ҳ?档</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>??????????</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>406 - ?ͻ?????????????? MIME ???͵?????ҳ?档</h2>
  <h3>??????޷?????Ҫ???ҵ?ҳ?棬??Ϊ??ҳ?????һ????????????ܵ??ļ???չ????</h3>
 </fieldset></div>
</div>
</body>
</html>

**Comment by hibijun** [comment]
@itbdw  
![图片](https://user-images.githubusercontent.com/55735756/97767698-c91b1780-1b58-11eb-9857-ee602361b1cd.png)
header  在上传的时候被更改了。  这个是正确的， 我线上，线下都能使用。

**Comment by itbdw** [comment]
好的，测试还是没通

联系作者了，说近期会解决带宽问题。

**Comment by itbdw** [comment]
目前cz88.net网站整改了

放弃自动更新了
