### ISSUE TITLE
这个IP数据量有多大

### ISSUE THREAD

**Issue by shartoo** [itbdw/ip-database#22]
请问数据库中IP数量有多少？

**Comment by itbdw** [comment]
QQ IP数据库 纯真版20200930

IP数据记录：527250条
数据库大小：9M
      
	收集了包括中国电信、中国移动、中国联通、长城宽带、聚友宽带等 ISP 的 IP 地址数据，包括网吧数据。
希望能够通过大家的共同努力打造一个没有未知数据，没有错误数据的QQ IP。IP数据库每5天更新一次，请大家
定期更新IP数据库！
	因为IP地址数据是民间收集的，各运营商也会不时的更改IP段，所以有点遗漏、错误是难免的。随数据库附
送IP解压，查询软件。假如发现IP地址有不对的，或想提供新的IP地址，请到纯真IP小秘书提供IP地址数据，或者登陆
纯真时空论坛“电脑板块”中的“代理及IP板”块告诉我们。,以便及时更新IP数据库。谢谢！

★★★★★★★★★★★★★★★★★★★★★★★★
在线升级数据库：
	随数据库附送的查询程序（ip.exe）具有在线检测并升级IP数据库的功能，只要运行该程序，点击右上角的
“在线升级”，就可以升级IP数据库到新的版本，无需再到下载网站下载新版的IP数据库。
★★★★★★★★★★★★★★★★★★★★★★★★


IP小秘书：http://www.cz88.net/ip
纯真网络：http://www.cz88.net
纯真时空论坛：http://bbs.cz88.net

金狐  QQ:486126  EMail:admin@cz88.net

**Comment by shartoo** [comment]
感谢！ 这个`qqwry.dat`有没有JSON格式啊，这个dat格式其他语言解析不了。我用python json就没法解析出来~

**Comment by itbdw** [comment]
https://github.com/search?q=python+qqwry

这套代码太久远了，太破了。正在重构代码，其实获取的最初的地址是 `北京市 师傅师傅师傅师傅` 这样的地址，只要自己实现格式化就好了

**Comment by shartoo** [comment]
感谢分享~
