### ISSUE TITLE
v3.x 可以支持 PHP8不

### ISSUE THREAD

**Issue by iMactool** [itbdw/ip-database#26]
Problem 1
    - Root composer.json requires itbdw/ip-database ^3.0 -> satisfiable by itbdw/ip-database[3.0.0].
    - itbdw/ip-database 3.0.0 requires php ~5.4|~7.0 -> your php version (8.0.8) does not satisfy that requirement.

**Comment by itbdw** [comment]
好了，直接接受所有版本了
