### ISSUE TITLE
Warning: gzuncompress(): data error

### ISSUE THREAD

**Issue by jianghua** [itbdw/ip-database#35]
您好，执行bin/update-ip.php时报错，您有空的时候帮忙看看
![image](https://user-images.githubusercontent.com/1780001/194979258-631cf647-fccd-4505-b6f9-4898d01625ef.png)

**Comment by hulang** [comment]
@jianghua 你不知道 纯真IP库 ，已经停止自动更新了吗？必须要关注他们的公众号，他们会隔10天左右发布一次更新。。
真是很烦。。。

**Comment by itbdw** [comment]
刚才确认了下，是纯真IP网站套了一层 cloudflare，导致没有过认证

**Comment by ghost** [comment]
现在更新不能是吧？

**Comment by ghost** [comment]
这个现在能解决吗？

**Comment by itbdw** [comment]
目前纯真IP开始推广收费项目了，无法自动更新。建议手动更新替换
