### ISSUE TITLE
3.0版本无法支持php8+吗

### ISSUE THREAD

**Issue by xianrenqh** [itbdw/ip-database#38]
3.0版本无法支持php8+吗

**Comment by xianrenqh** [comment]
![image](https://user-images.githubusercontent.com/16522281/205540988-8969c0cc-9d1c-400a-8825-27b68c574ea6.png)

**Comment by hulang** [comment]
@xianrenqh 不应该啊。。。我看composer.json里面没有限制PHP版本啊。。。你是不是哪里搞错了。无论是v2/v3扩展composer.json里面都没有限制PHP版本
"php": "*",

**Comment by keven1024** [comment]
> @xianrenqh 不应该啊。。。我看composer.json里面没有限制PHP版本啊。。。你是不是哪里搞错了。无论是v2/v3扩展composer.json里面都没有限制PHP版本 "php": "*",

@hulang 更新到3.0.1解决

![image](https://user-images.githubusercontent.com/99848979/211290196-a99e38a4-4839-43ee-ace4-c4096fb656e8.png)


![image](https://user-images.githubusercontent.com/99848979/211290000-58b3d1f8-2237-459b-88da-503a590090a8.png)

**Comment by hulang** [comment]
@keven1024 收到。。。

**Comment by xianrenqh** [comment]
好的哦
