### ISSUE TITLE
请问ipv6数据库纯真没找到呢

### ISSUE THREAD

**Issue by hexsen929** [itbdw/ip-database#41]
ipv6wry.db软件安装后只有qqwry.dat，ipv6的数据文件不知道有地址不。

**Comment by hulang** [comment]
https://github.com/itbdw/ip-database/issues/21

**Comment by itbdw** [comment]
> ipv6wry.db软件安装后只有qqwry.dat，ipv6的数据文件不知道有地址不。

需要安装3.0以上版本 `composer require 'itbdw/ip-database' ^3.0`
