### ISSUE TITLE
一个疑问，是这样的，我复制作者到创建的仓库，就出现一个问题

### ISSUE THREAD

**Issue by hulang** [itbdw/ip-database#42]
主要是我一直用国内：阿里云镜像，快啊。
但是无法安装作者你写的。。用原生`repo.packagist.org`慢啊。。
这是我自己复制到我仓库的：`https://github.com/hulang/think-ip`
目前出现一个问题，一直提示错误：
`unpack(): Type V: not enough input, need 4, have 1`
如果可以，作者你指点下啊。。最好能使用：阿里云镜像更新。。。我就不用复制仓库了。。
@itbdw

**Comment by hulang** [comment]
解决了。。。我依旧使用作者你的库，用：阿里云。。
`composer.json`里面设置成了dev。。。
```shell
"itbdw/ip-database": "^3.x-dev"
```

**Comment by hulang** [comment]
我认为应该作者需要在：packagist.org里面删除dev，再更新一下版本到：3.0.2，阿里云应该就可以正常更新了。
更新的时候，顺便可以把：纯真IP库更新一下。。。

**Comment by itbdw** [comment]
刚发布了 3.0.2
https://packagist.org/packages/itbdw/ip-database

检查了源站，是可用的 
https://repo.packagist.org/p2/itbdw/ip-database.json

阿里云应该是出问题了，无法识别新的release，而且通过观察他给出的地址，发现zip包还是在github下载的，很慢的。 https://mirrors.aliyun.com/composer/p2/itbdw/ip-database.json

腾讯是可用的，而且zip包也是直接在腾讯下载，建议使用腾讯 🥇 
https://mirrors.cloud.tencent.com/repository/composer/p/itbdw/ip-database.json
