### ISSUE TITLE
当为ipv6时，获取到的城市city信息，有多余的“中国区” 三个字

### ISSUE THREAD

**Issue by egege** [itbdw/ip-database#43]
之前的3.0.0版本
<img width="1489" alt="截屏2024-02-06 15 17 27" src="https://github.com/itbdw/ip-database/assets/23636455/2d161a6a-e73f-4f69-b77c-065e58dc62c8">
最新的3.0.2版本
<img width="1487" alt="截屏2024-02-06 15 42 07" src="https://github.com/itbdw/ip-database/assets/23636455/3fd1ffd4-12d7-42ed-8e78-39351f40375b">

**Comment by itbdw** [comment]
考虑到不同的城市可能包含区， 这个不太好处理
