### ISSUE TITLE
某些IP的市这个值是乱码

### ISSUE THREAD

**Issue by yu1ec** [itbdw/ip-database#8]
比如：120.193.188.229

看了下，貌似是ltrim引起的问题，ltrim，rtrim啥的不支持中文的，建议使用mb_substr来进行切割

**Comment by itbdw** [comment]
已解决，感谢

**Comment by yu1ec** [comment]
哈哈， 我刚写好hotfix，刚准备提交

**Comment by itbdw** [comment]
我错了，应该等你 😸 

你是怎么写的？我来学习一下。

**Comment by yu1ec** [comment]
一个思路，还有希望能更新下ip库，貌似qqwry已经更新到了3月份了

**Comment by yu1ec** [comment]
并且还有个问题，不知道是不是缓存问题，我composer update不下来新的版本

**Comment by itbdw** [comment]
我github和packgist是绑定的，以前都可以升级的，不知为何刚才那边没更新，手动更新到2.0.4了。

qqwry这个文件我这边现在不方便更新，新装的双系统，Windows里以前没装cz88，我刚去官网下载软件，无法打开了，不知为何。如果你方便的话，可以升级下数据库，然后提个 PR

**Comment by itbdw** [comment]
刚才使用国外 ip 成功下载，并更新了 qqwry 版本了。可能纯真软件国内服务器挂了。
